name: Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main  # Deploys only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify dist directory exists
        run: |
          echo "Checking if dist directory exists:"
          ls -la
          if [ -d "dist" ]; then
            echo "Dist directory found:"
            ls -la dist/
          else
            echo "No dist directory found! Build might have failed."
            exit 1
          fi

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./dist          # Vite build folder
          server-dir: ${{ secrets.REMOTE_DIR }}  # Should point directly to /public_html
          dangerous-clean-slate: true  # Clears old files before deployment
